# Generated by Django 5.0.1 on 2024-01-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='images/random.jpg', upload_to='func'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='português', max_length=150),
        ),
    ]
