# Generated by Django 5.0.1 on 2024-01-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0002_employee_address_employee_contact_employee_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='portuguesa', max_length=150),
        ),
    ]
