# Generated by Django 5.0.1 on 2024-01-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0003_alter_employee_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='random.jpg', upload_to='func'),
        ),
    ]
