# Generated by Django 5.0.1 on 2024-01-28 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0005_productionstatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstatistics',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='human.employee'),
        ),
    ]
