# Generated by Django 5.0.1 on 2024-01-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0006_alter_productionstatistics_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductionStatistics',
        ),
    ]
