# Generated by Django 5.0.1 on 2024-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Produto')),
                ('description', models.TextField(default=' Sem Descrição ', verbose_name='Descrição')),
                ('price', models.FloatField(help_text='euros cada', verbose_name='Preço')),
                ('category', models.CharField(blank=True, choices=[('SHIELD', 'SHIELD'), ('BRACKET', 'BRACKET'), ('ASSEMBLY', 'HANGER ASSEMBLY')], max_length=20, verbose_name='Categoria')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
