# Generated by Django 5.0.1 on 2024-01-24 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade Produzida')),
                ('time', models.IntegerField(verbose_name='Tempo de Produção')),
                ('date', models.DateTimeField(verbose_name='Data de Produção')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human.employee')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Inventary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantidade Total')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('productions', models.ManyToManyField(to='product.production')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade da Ordem')),
                ('state', models.CharField(choices=[('P', 'Pendente'), ('EA', 'Em Produção'), ('C', 'Concluída')], default='P', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produto')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productionorder'),
        ),
    ]
