# Generated by Django 5.0.1 on 2024-01-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_production_inventary_productionorder_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionorder',
            old_name='quantity',
            new_name='quantity_ordered',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quantity_produced',
            field=models.IntegerField(default=0, verbose_name='Quantidade Produzida'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='state',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('EA', 'Em Produção'), ('C', 'Concluída')], max_length=2, null=True),
        ),
    ]
