# Generated by Django 5.0.1 on 2024-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_quantity_productionorder_quantity_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='production_order',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='productions',
            field=models.ManyToManyField(to='product.production'),
        ),
    ]
