# Generated by Django 5.0.1 on 2024-01-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_production_production_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='productions',
            field=models.ManyToManyField(blank=True, to='product.production'),
        ),
    ]
