# Generated by Django 5.0.1 on 2024-01-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productionorder_productions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='productions',
        ),
    ]
