# Generated by Django 5.0.1 on 2024-01-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_production_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productionorder'),
        ),
    ]
