# Generated by Django 5.0 on 2024-02-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='prod_order_id',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
