# Generated by Django 5.0.1 on 2024-01-28 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human', '0007_delete_productionstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_production_quantity', models.IntegerField(default=0, verbose_name='Total de Quantidade Produzida')),
                ('average_production_time', models.FloatField(default=0, verbose_name='Tempo Médio de Produção por Unidade')),
                ('production_efficiency', models.FloatField(default=0, verbose_name='Eficiência de Produção')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='human.employee')),
            ],
        ),
    ]
