# Generated by Django 5.0.1 on 2024-01-28 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_image'),
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstatistics',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.CreateModel(
            name='ProductStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_production_quantity', models.IntegerField(default=0, verbose_name='Total de Quantidade Produzida')),
                ('average_production_time', models.FloatField(default=0, verbose_name='Tempo Médio de Produção por Unidade')),
                ('production_efficiency', models.FloatField(default=0, verbose_name='Eficiência de Produção')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
