# Generated by Django 5.0 on 2024-02-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery',
            new_name='delivery_date',
        ),
    ]
