# Generated by Django 5.0 on 2024-02-14 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human', '0008_client_profile'),
        ('orders', '0004_rename_delivery_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='human.profile'),
        ),
    ]
