# Generated by Django 5.0 on 2024-02-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_salesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
